spring.application.name=demo

# Configuración de la DB
spring.datasource.url=jdbc:mysql://localhost:3306/searchsport?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Secret Key
jwt.secret=Y2xhdmVzZWNyZXRhcGFyYXNlYXJjaHNwb3J0cHJveWVjdG9zZW1lc3RyYWwyMDI0ZXh0cmFsYXJnYQ==